name: GlobalVillagerCuring
version: '${project.version}'
main: com.github.sebseb7.globalvillagercuring
api-version: 1.20
authors: [ gwodny,sebseb7 ]
description: Allows villager curing to apply to all players.
